### ISSUE TITLE
运行报错麻烦帮忙看下

### ISSUE THREAD

**Issue by DifferentSparkler** [interestingcn/365E5_subscription#1]
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '396c2760-2fa5-4948-b9d5-9839a7440836'.\r\nTrace ID: 3ce379e4-441f-4eae-9730-fc0220183001\r\nCorrelation ID: 54752956-bf4f-48f1-b808-6ecae2522f59\r\nTimestamp: 2022-06-18 03:16:39Z","error_codes":[7000215],"timestamp":"2022-06-18 03:16:39Z","trace_id":"3ce379e4-441f-4eae-9730-fc0220183001","correlation_id":"54752956-bf4f-48f1-b808-6ecae2522f59","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
=======================================
任务结束：2022-06-[1](https://github.com/DifferentSparkler/365E5_subscription/runs/6945426659?check_suite_focus=true#step:6:1)8 [11](https://github.com/DifferentSparkler/365E5_subscription/runs/6945426659?check_suite_focus=true#step:6:12):16
=======================================

**Comment by interestingcn** [comment]
> 

核查下id和密钥是否准确，相对应的权限是否已经给予授权，先本地运行成功后再使用Actions  ：）
